version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: shopper-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drivers_shopper
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
volumes:
  postgres-data:
